### ISSUE TITLE
BASE_URL i app.constants

### ISSUE THREAD

**Issue by alexdriaguine** [fh222dt/fh222dt_client_app#1]
Var satt till cloud9-url. Borde sättas till localhost:3000 eller stå med i instruktioner att man själv måste ändra den

**Comment by alexdriaguine** [comment]
Var även tvungen att ändra nyckeln eftersom den autogenereras vid db:setup

**Comment by fh222dt** [comment]
Ska skriva tydligare instruktioner, är så van själv vid vad man ska göra så det blev svårt att skriva ner allt ordentligt :)
